### ISSUE TITLE
Coordenadas

### ISSUE THREAD

**Issue by ifreddyrondon** [zokeber/venezuela-json#4]
Esta muy bueno el aporte, seria genial agregar las posiciones gps.

Saludos y gracias

**Comment by jobsamuel** [comment]
¡Hola @spantons! :smiley: 

¿Te refieres a las coordenadas de cada municipio y/o parroquia? Por ejemplo:

            {
                "municipio": "Maracaibo",
                "capital": "Maracaibo",
                "coordenadas": {
                    "latitud": 10.6333333,
                    "longitud": 071.6333333   
                },
                "parroquias": [ ... ]
            },

Un gusto saber que te parece bueno el aporte :beers:

**Comment by spantons** [comment]
Buen día @jobsamuel si me refería a las coordenadas de cada municipio y parroquia, justo con el formato que estas especificando:

"coordenadas": {
    "latitud": 10.6333333,
    "longitud": 71.6333333   
},
 
De esta manera seria bastante fácil cargar la data y pintar marcadores en un mapa de google por ejemplo.

Saludos.

**Comment by zokeber** [comment]
Hola! ¿Te refieres en formato geoJSON? puede ser un feature a futuro, pero puedes mirar acá:

1. https://miv.cenditel.gob.ve/ecoalba/browser/ecoalba/media/geojson/venezuela.geojson?rev=fd9dc646672fbe5121be637b6a8b398fffb0793f

2. https://github.com/AshKyd/geojson-regions/blob/master/data/countries/ne_50m_admin_0_countries.geo.json/venezuela.json

**Comment by abr4xas** [comment]
También las coordenadas pueden servir para usar openweathermap.org y obtener información del clima :+1:

**Comment by jobsamuel** [comment]
Me gusta ésta nueva *feature*. Entonces pondré manos a la obra :sunglasses: (pero sólo empezaré con las capitales de cada Estado :sweat_smile:). Para todo lo demás, creo que @zokeber y yo necesitaremos ayuda.

¿Qué dicen @spantons @abr4xas? ¿Nos echan una mano?

**Comment by abr4xas** [comment]
@jobsamuel Claro, cuenta conmigo :D

**Comment by abr4xas** [comment]
Btw, aunque no tiene nada que ver quisiera que revisaran [esto](https://github.com/abr4xas/bancos-json)  contiene los nombres de los bancos de .ve con sus códigos me gustaría que le dieran una revisada y me comentaran por allá sus opiniones :)

**Comment by spantons** [comment]
@jobsamuel dale claro que si

**Comment by zokeber** [comment]
Hola. 

Disculpen la demora, si @jobsamuel es un buen feature, habría que definir de donde se tomarían las coordenadas para armar el GeoJSON, ¿alguna sugerencia? o ¿se usan las que facilité?

**Comment by rcitterio** [comment]
Saludos amigos

 @jobsamuel una duda puedo usarlo tambien para una bd de mysql con php es que deseo implementar su archivo por el mapeo de las ciudades para usar esto https://github.com/Aerolab/acanohayluz

Excelente contribución 

gracias de antemano por su valiosa colaboración.
